### ISSUE TITLE
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).

### ISSUE THREAD

**Issue by miguelmota** [blocknative/notify#112]
Hey Aaron, looks a like dependency is preforming an eval check which causes the content security policy to fail when 'unsafe-eval' is not allowed. This is on firefox 74

![Screenshot from 2020-03-30 17-12-34](https://user-images.githubusercontent.com/168240/77979238-ef25c400-72b8-11ea-8a6b-684b4dd17018.png)

![Screenshot from 2020-03-30 17-08-15](https://user-images.githubusercontent.com/168240/77979247-f51ba500-72b8-11ea-84da-5b143cc5d8ee.png)

To reproduce, set the content security policy in your html file

```
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'self'; connect-src 'self' wss://api.blocknative.com" />
```

**Comment by aaronbarnardsound** [comment]
No worries I will have a look in to this and see if I can find out what is happening here. Thanks Miguel 👍

**Comment by aaronbarnardsound** [comment]
Hey @miguelmota did you find that this is something that has been introduced recently?

**Comment by miguelmota** [comment]
@Aaron Barnard#7646 sorry i missed this message. I don't have much context around that issue since it's been a while but seems related to this https://github.com/ethereum/web3.js/issues/3439

You may close it if it's unrelated notify.js

**Comment by aaronbarnardsound** [comment]
No worries, will close this for the moment as it is unrelated to Notify directly and it is unclear which dependency it is coming from.
