### ISSUE TITLE
TransactionEventCode is outdated

### ISSUE THREAD

**Issue by gorgos** [blocknative/notify#160]
The `TransactionEventCode` seems to have outdated keys: https://github.com/blocknative/notify/blob/f8f51806fef70145ca6f684ac850ad3d22c9e4d1/src/interfaces.ts#L25-L40

From what I can see those are the working event keys: https://docs.blocknative.com/notify-sdk#event-codes. And those ones are outdated: https://docs.blocknative.com/notify#event-codes.

It would be great if the `TransactionEventCode` could reflect the working event codes. And it also would be great to know if those event codes: https://docs.blocknative.com/notify#event-code will be supported in the future.

**Comment by aaronbarnardsound** [comment]
Hey @gorgos, thanks for pointing this out. The difference that you see between the event codes listed in the SDK documentation vs the event codes that are listed in the Notify.js docs are the extra "pre-flight" events that Notify will create client side when using the `transaction` function. I have updated the Notify docs to make this more clear: https://docs.blocknative.com/notify#event-codes
