### ISSUE TITLE
Closing the notification triggers onclick instead

### ISSUE THREAD

**Issue by andytcf** [blocknative/notify#172]
### Issue

When the autoDismiss flag is set to false and an onclick handler is attached, clicking the close button on the notification opens the link instead and does not let the user dismiss the notification. User will have to refresh their page to dismiss it.

### Example Code

```
	let { emitter } = notify.hash(hash);
	emitter.on('txConfirmed', result => {
		setTimeout(() => {
			callback();
		}, 15000);
		return {
			message: message ? message : undefined,
			onclick: () => {
				window.open(
					`${getEtherscanTxLink(networkId, result.hash)}`,
					'_blank',
					'noopener, norefferer'
				);
			},
			autoDismiss: false,
		};
	});```

**Comment by AndyTCF** [comment]
Also would be great to have a "link" prop that automatically handles the href instead of using window.open()

**Comment by aaronbarnardsound** [comment]
@andytcf That bug is fixed and I also added the `link` prop to the notification customization object in version `1.5.0`. Full release notes here: https://github.com/blocknative/notify/releases/tag/1.5.0

**Comment by andytcf** [comment]
@aaronbarnardsound amazing work! thanks
