### ISSUE TITLE
autoDismiss type issue

### ISSUE THREAD

**Issue by evgenyboxer** [blocknative/notify#177]
The docs - https://docs.blocknative.com/notify#emitter suggest that `autoDismiss` needs to be `false` if I wish to disable it. However, the type is set to `number` so `false` would result in a TypeScript error (My workaround is to use `0` which works well). 
This is the line I'm referring to - https://github.com/blocknative/notify/blob/master/src/interfaces.ts#L79

I have a couple of suggestions for a potential solution - 
1. Convert the type to: `number | false` (then only trigger the dismissal if `autoDismiss` is a number).
2. Keep it as numeric but change the docs to reflect that `0` means it's disabled.

Keep up the awesome work, love this library 👍

**Comment by aaronbarnardsound** [comment]
Hey @evgenyboxer yes that's a good pickup. I went for your second suggestion and updated the docs. Thanks! 😄
