### ISSUE TITLE
txConfirmed and txFailed events are not called after transaction is completed.

### ISSUE THREAD

**Issue by totop716** [blocknative/notify#214]
I am using bnc-notify package for transaction notifications.
initialized the `notify` object and getting `emitter` object like this.

`const notify = Notify({
    dappId: process.env.REACT_APP_BLOCKNATIVE_KEY,
    networkId: chainId
})
const { emitter } = notify.hash(tx.hash);`

but `emitter` object does not emit `txConfirmed` and `txFailed` events.
it emits `txCancel` and `txSent` events.
Could you check this issue?

Thanks.

**Comment by aaronbarnardsound** [comment]
@totop716 this should be fixed in the [v1.9.3](https://github.com/blocknative/notify/releases/tag/1.9.3)
