### ISSUE TITLE
Polygon Mumbai Testnet Support

### ISSUE THREAD

**Issue by georgeperry1** [blocknative/notify#221]
Hey,

I'm having an issue when trying to display the Notifier when performing transactions through Polygon Mumbai Testnet. We recently switched from Ethereum Mainnet and Rinkeby Testnet, where it worked just fine and we saw the Notifier pop-up. Is there currently support for these two networks?

For context, we are plugged into a NextJS app and there is not even any errors displaying when the transaction is successfully completed. 

Thanks you!

**Comment by aaronbarnardsound** [comment]
@georgeperry1 Are you still having issues receiving Mumbai notifications? They should be supported and working as expected, but feel free to reopen if you still see this issue.
