### ISSUE TITLE
Support Astar/Shiden/Shibuya network

### ISSUE THREAD

**Issue by impelcrypto** [blocknative/notify#225]
It would be helpful if `notify` could integrate with Astar/Shiden/Shibuya EVM network.

https://docs.astar.network/integration/network-details
https://docs.astar.network/build/smart-contracts/ethereum-virtual-machine/common-questions-for-evm-smart-contract-deployment

**Comment by Hana0916** [comment]
I did ASTR farming, but when I select the combination of WASTR and WETH in Add Liquidity of POOL, an error occurs. Please help me what to do

**Comment by impelcrypto** [comment]
Hey @Hana0916 
You are asking question in wrong repository. I think you should go to ask Arthswap on Discord or Twitter. https://twitter.com/arthswap

**Comment by Hana0916** [comment]
Thank you, I will try.

2022年2月10日(木) 11:32 impelcrypto ***@***.***>:

**Comment by impelcrypto** [comment]
Hi @taylorjdawson 
Could you update about this issue, please?

**Comment by aaronbarnardsound** [comment]
Integrating with those networks would require Blocknative to add infrastructure (running nodes for those networks) which is not likely to happen at this point due to lack of demand. Feel free to jump in our [Discord](https://discord.com/invite/KZaBVME) to start a discussion on adding these chains.
