### ISSUE TITLE
Unauthorized Chain in Tier

### ISSUE THREAD

**Issue by pvdyck** [blocknative/notify#237]
<img width="560" alt="Capture d’écran 2022-06-22 à 12 34 05" src="https://user-images.githubusercontent.com/460696/174951386-5b2b1b95-d959-4261-b59a-f777082a9ddb.png">

Using chain id 1337 for localhost in hardhat config ... is it related ?

**Comment by aaronbarnardsound** [comment]
Hey @pvdyck I am looking in to this. It might be due to some recent server changes.

**Comment by aaronbarnardsound** [comment]
In the meantime, you can add a function to handle errors when initializing via the `onerror` parameter and just ignore that error as local networks do not use the WebSocket connection to our server.

**Comment by aaronbarnardsound** [comment]
@pvdyck This was indeed a server issue and should now be fixed.

**Comment by pvdyck** [comment]
@aaronbarnardsound thanks a lot

**Comment by goums** [comment]
hey @aaronbarnardsound 
we are currently facing the same issue with BSC (chain id 56)
could check if it's also something wrong on your server?

**Comment by re2005** [comment]
Having same issue on `56 Binance Smart Chain`

**Comment by aaronbarnardsound** [comment]
Hey @goums this error is introduced due a change on our backend infrastructure. BSC is no longer supported on our free tier and requires a [production 2 plan](https://www.blocknative.com/pricing) due to the expensive nature of supporting BSC notifications.

**Comment by goums** [comment]
thanks for your reply @aaronbarnardsound 
make sense given the high cost of BSC nodes
